3.5.0:
	docker build --build-arg R_VERSION=3.5.0 --build-arg BUILD_DATE=2018-07-02 --build-arg UBUNTU_VERSION=18.04 --tag r-base:3.5.0 .


3.4.4:
	docker build --build-arg R_VERSION=3.4.4 --build-arg BUILD_DATE=2018-04-23 --build-arg UBUNTU_VERSION=16.04 --tag r-base:3.4.4 .

3.4.3:
	docker build --build-arg R_VERSION=3.4.3 --build-arg BUILD_DATE=2018-03-15 --build-arg UBUNTU_VERSION=16.04 --tag r-base:3.4.3 .

3.4.2:
	docker build --build-arg R_VERSION=3.4.2 --build-arg BUILD_DATE=2017-11-30 --build-arg UBUNTU_VERSION=16.04 --tag r-base:3.4.2 .

3.4.1:
	docker build --build-arg R_VERSION=3.4.1 --build-arg BUILD_DATE=2017-09-28 --build-arg UBUNTU_VERSION=16.04 --tag r-base:3.4.1 .

3.4.0:
	docker build --build-arg R_VERSION=3.4.0 --build-arg BUILD_DATE=2017-06-30 --build-arg UBUNTU_VERSION=16.04 --tag r-base:3.4.0 .
