3.5.2:
	docker build --build-arg R_VERSION=3.5.2 --build-arg BUILD_DATE=2019-03-10 --tag r-minimal:3.5.2 3.5.2/

3.5.1:
	docker build --build-arg R_VERSION=3.5.1 --build-arg BUILD_DATE=2018-12-19 --tag r-minimal:3.5.1 3.5.1/

3.5.0:
	docker build --build-arg R_VERSION=3.5.0 --build-arg BUILD_DATE=2018-07-02 --tag r-minimal:3.5.0 3.5.0/


3.4.4:
	docker build --build-arg R_VERSION=3.4.4 --build-arg BUILD_DATE=2018-04-23 --tag r-minimal:3.4.4 3.4/

3.4.3:
	docker build --build-arg R_VERSION=3.4.3 --build-arg BUILD_DATE=2018-03-15 --tag r-minimal:3.4.3 3.4/

3.4.2:
	docker build --build-arg R_VERSION=3.4.2 --build-arg BUILD_DATE=2017-11-30 --tag r-minimal:3.4.2 3.4/

3.4.1:
	docker build --build-arg R_VERSION=3.4.1 --build-arg BUILD_DATE=2017-09-28 --tag r-minimal:3.4.1 3.4/

3.4.0:
	docker build --build-arg R_VERSION=3.4.0 --build-arg BUILD_DATE=2017-06-30 --tag r-minimal:3.4.0 3.4/
